
package introsde.finalproject.soap.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "People", targetNamespace = "http://ws.soap.finalproject.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface People {


    /**
     * 
     * @param person
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.CreatePersonResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/createPersonRequest", output = "http://ws.soap.finalproject.introsde/People/createPersonResponse")
    public int createPerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param personId
     * @return
     *     returns introsde.finalproject.soap.ws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetPersonResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/getPersonRequest", output = "http://ws.soap.finalproject.introsde/People/getPersonResponse")
    public Person getPerson(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param person
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.UpdatePersonResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/updatePersonRequest", output = "http://ws.soap.finalproject.introsde/People/updatePersonResponse")
    public int updatePerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param personId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "responsePersonCode", targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.DeletePersonResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/deletePersonRequest", output = "http://ws.soap.finalproject.introsde/People/deletePersonResponse")
    public int deletePerson(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @return
     *     returns introsde.finalproject.soap.ws.ListPersonWrapper
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "getPeopleList", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetPeopleList")
    @ResponseWrapper(localName = "getPeopleListResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetPeopleListResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/getPeopleListRequest", output = "http://ws.soap.finalproject.introsde/People/getPeopleListResponse")
    public ListPersonWrapper getPeopleList();

    /**
     * 
     * @param personId
     * @return
     *     returns introsde.finalproject.soap.ws.ListMeasureWrapper
     */
    @WebMethod
    @WebResult(name = "currentHealth", targetNamespace = "")
    @RequestWrapper(localName = "getCurrentHealth", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetCurrentHealth")
    @ResponseWrapper(localName = "getCurrentHealthResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetCurrentHealthResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/getCurrentHealthRequest", output = "http://ws.soap.finalproject.introsde/People/getCurrentHealthResponse")
    public ListMeasureWrapper getCurrentHealth(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param personId
     * @return
     *     returns introsde.finalproject.soap.ws.ListMeasureWrapper
     */
    @WebMethod
    @WebResult(name = "vitalSigns", targetNamespace = "")
    @RequestWrapper(localName = "getVitalSigns", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetVitalSigns")
    @ResponseWrapper(localName = "getVitalSignsResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetVitalSignsResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/getVitalSignsRequest", output = "http://ws.soap.finalproject.introsde/People/getVitalSignsResponse")
    public ListMeasureWrapper getVitalSigns(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param doctor
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "doctorId", targetNamespace = "")
    @RequestWrapper(localName = "createDoctor", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.CreateDoctor")
    @ResponseWrapper(localName = "createDoctorResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.CreateDoctorResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/createDoctorRequest", output = "http://ws.soap.finalproject.introsde/People/createDoctorResponse")
    public int createDoctor(
        @WebParam(name = "doctor", targetNamespace = "")
        Doctor doctor);

    /**
     * 
     * @param doctorId
     * @return
     *     returns introsde.finalproject.soap.ws.Doctor
     */
    @WebMethod
    @WebResult(name = "doctor", targetNamespace = "")
    @RequestWrapper(localName = "getDoctor", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetDoctor")
    @ResponseWrapper(localName = "getDoctorResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetDoctorResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/getDoctorRequest", output = "http://ws.soap.finalproject.introsde/People/getDoctorResponse")
    public Doctor getDoctor(
        @WebParam(name = "doctorId", targetNamespace = "")
        int doctorId);

    /**
     * 
     * @param doctor
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "doctorId", targetNamespace = "")
    @RequestWrapper(localName = "updateDoctor", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.UpdateDoctor")
    @ResponseWrapper(localName = "updateDoctorResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.UpdateDoctorResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/updateDoctorRequest", output = "http://ws.soap.finalproject.introsde/People/updateDoctorResponse")
    public int updateDoctor(
        @WebParam(name = "doctor", targetNamespace = "")
        Doctor doctor);

    /**
     * 
     * @param doctorId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "responseDoctorCode", targetNamespace = "")
    @RequestWrapper(localName = "deleteDoctor", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.DeleteDoctor")
    @ResponseWrapper(localName = "deleteDoctorResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.DeleteDoctorResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/deleteDoctorRequest", output = "http://ws.soap.finalproject.introsde/People/deleteDoctorResponse")
    public int deleteDoctor(
        @WebParam(name = "doctorId", targetNamespace = "")
        int doctorId);

    /**
     * 
     * @param idDoctor
     * @return
     *     returns introsde.finalproject.soap.ws.ListPersonWrapper
     */
    @WebMethod
    @WebResult(name = "patientList", targetNamespace = "")
    @RequestWrapper(localName = "getPersonByDoctor", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetPersonByDoctor")
    @ResponseWrapper(localName = "getPersonByDoctorResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetPersonByDoctorResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/getPersonByDoctorRequest", output = "http://ws.soap.finalproject.introsde/People/getPersonByDoctorResponse")
    public ListPersonWrapper getPersonByDoctor(
        @WebParam(name = "idDoctor", targetNamespace = "")
        int idDoctor);

    /**
     * 
     * @param familyId
     * @return
     *     returns introsde.finalproject.soap.ws.Family
     */
    @WebMethod
    @WebResult(name = "family", targetNamespace = "")
    @RequestWrapper(localName = "getFamily", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetFamily")
    @ResponseWrapper(localName = "getFamilyResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetFamilyResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/getFamilyRequest", output = "http://ws.soap.finalproject.introsde/People/getFamilyResponse")
    public Family getFamily(
        @WebParam(name = "familyId", targetNamespace = "")
        int familyId);

    /**
     * 
     * @param idPerson
     * @param reminder
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "reminder", targetNamespace = "")
    @RequestWrapper(localName = "createReminder", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.CreateReminder")
    @ResponseWrapper(localName = "createReminderResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.CreateReminderResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/createReminderRequest", output = "http://ws.soap.finalproject.introsde/People/createReminderResponse")
    public int createReminder(
        @WebParam(name = "reminder", targetNamespace = "")
        Reminder reminder,
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson);

    /**
     * 
     * @param personId
     * @return
     *     returns introsde.finalproject.soap.ws.ListReminderWrapper
     */
    @WebMethod
    @WebResult(name = "reminder", targetNamespace = "")
    @RequestWrapper(localName = "getReminder", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetReminder")
    @ResponseWrapper(localName = "getReminderResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetReminderResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/getReminderRequest", output = "http://ws.soap.finalproject.introsde/People/getReminderResponse")
    public ListReminderWrapper getReminder(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param reminder
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "updateReminder", targetNamespace = "")
    @RequestWrapper(localName = "updateReminder", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.UpdateReminder")
    @ResponseWrapper(localName = "updateReminderResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.UpdateReminderResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/updateReminderRequest", output = "http://ws.soap.finalproject.introsde/People/updateReminderResponse")
    public int updateReminder(
        @WebParam(name = "reminder", targetNamespace = "")
        Reminder reminder);

    /**
     * 
     * @param idReminder
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "responseReminderCode", targetNamespace = "")
    @RequestWrapper(localName = "deleteReminder", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.DeleteReminder")
    @ResponseWrapper(localName = "deleteReminderResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.DeleteReminderResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/deleteReminderRequest", output = "http://ws.soap.finalproject.introsde/People/deleteReminderResponse")
    public int deleteReminder(
        @WebParam(name = "idReminder", targetNamespace = "")
        int idReminder);

    /**
     * 
     * @param idPerson
     * @param target
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "targets", targetNamespace = "")
    @RequestWrapper(localName = "createTarget", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.CreateTarget")
    @ResponseWrapper(localName = "createTargetResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.CreateTargetResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/createTargetRequest", output = "http://ws.soap.finalproject.introsde/People/createTargetResponse")
    public int createTarget(
        @WebParam(name = "target", targetNamespace = "")
        Target target,
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson);

    /**
     * 
     * @param personId
     * @return
     *     returns introsde.finalproject.soap.ws.ListTargetWrapper
     */
    @WebMethod
    @WebResult(name = "targets", targetNamespace = "")
    @RequestWrapper(localName = "getTargetList", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetTargetList")
    @ResponseWrapper(localName = "getTargetListResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetTargetListResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/getTargetListRequest", output = "http://ws.soap.finalproject.introsde/People/getTargetListResponse")
    public ListTargetWrapper getTargetList(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param target
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "targetId", targetNamespace = "")
    @RequestWrapper(localName = "updateTarget", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.UpdateTarget")
    @ResponseWrapper(localName = "updateTargetResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.UpdateTargetResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/updateTargetRequest", output = "http://ws.soap.finalproject.introsde/People/updateTargetResponse")
    public int updateTarget(
        @WebParam(name = "target", targetNamespace = "")
        Target target);

    /**
     * 
     * @param idTarget
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "responseTargetCode", targetNamespace = "")
    @RequestWrapper(localName = "deleteTarget", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.DeleteTarget")
    @ResponseWrapper(localName = "deleteTargetResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.DeleteTargetResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/deleteTargetRequest", output = "http://ws.soap.finalproject.introsde/People/deleteTargetResponse")
    public int deleteTarget(
        @WebParam(name = "idTarget", targetNamespace = "")
        int idTarget);

    /**
     * 
     * @param idMeasureDef
     * @param personId
     * @return
     *     returns introsde.finalproject.soap.ws.ListTargetWrapper
     */
    @WebMethod
    @WebResult(name = "targets", targetNamespace = "")
    @RequestWrapper(localName = "getTarget", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetTarget")
    @ResponseWrapper(localName = "getTargetResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetTargetResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/getTargetRequest", output = "http://ws.soap.finalproject.introsde/People/getTargetResponse")
    public ListTargetWrapper getTarget(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "idMeasureDef", targetNamespace = "")
        int idMeasureDef);

    /**
     * 
     * @param measure
     * @param idPerson
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "createMeasure", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.CreateMeasure")
    @ResponseWrapper(localName = "createMeasureResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.CreateMeasureResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/createMeasureRequest", output = "http://ws.soap.finalproject.introsde/People/createMeasureResponse")
    public int createMeasure(
        @WebParam(name = "measure", targetNamespace = "")
        Measure measure,
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson);

    /**
     * 
     * @param personId
     * @return
     *     returns introsde.finalproject.soap.ws.ListMeasureWrapper
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "getMeasure", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetMeasure")
    @ResponseWrapper(localName = "getMeasureResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetMeasureResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/getMeasureRequest", output = "http://ws.soap.finalproject.introsde/People/getMeasureResponse")
    public ListMeasureWrapper getMeasure(
        @WebParam(name = "personId", targetNamespace = "")
        int personId);

    /**
     * 
     * @param measure
     * @return
     *     returns int
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(name = "idUpdatedMeasure", targetNamespace = "")
    @RequestWrapper(localName = "updateMeasure", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.UpdateMeasure")
    @ResponseWrapper(localName = "updateMeasureResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.UpdateMeasureResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/updateMeasureRequest", output = "http://ws.soap.finalproject.introsde/People/updateMeasureResponse", fault = {
        @FaultAction(className = ParseException_Exception.class, value = "http://ws.soap.finalproject.introsde/People/updateMeasure/Fault/ParseException")
    })
    public int updateMeasure(
        @WebParam(name = "measure", targetNamespace = "")
        Measure measure)
        throws ParseException_Exception
    ;

    /**
     * 
     * @param idMeasure
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "responseMeasureCode", targetNamespace = "")
    @RequestWrapper(localName = "deleteMeasure", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.DeleteMeasure")
    @ResponseWrapper(localName = "deleteMeasureResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.DeleteMeasureResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/deleteMeasureRequest", output = "http://ws.soap.finalproject.introsde/People/deleteMeasureResponse")
    public int deleteMeasure(
        @WebParam(name = "idMeasure", targetNamespace = "")
        int idMeasure);

    /**
     * 
     * @return
     *     returns introsde.finalproject.soap.ws.ListMeasureDefinitionWrapper
     */
    @WebMethod
    @WebResult(name = "measureDefinition", targetNamespace = "")
    @RequestWrapper(localName = "getMeasureDefinition", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetMeasureDefinition")
    @ResponseWrapper(localName = "getMeasureDefinitionResponse", targetNamespace = "http://ws.soap.finalproject.introsde/", className = "introsde.finalproject.soap.ws.GetMeasureDefinitionResponse")
    @Action(input = "http://ws.soap.finalproject.introsde/People/getMeasureDefinitionRequest", output = "http://ws.soap.finalproject.introsde/People/getMeasureDefinitionResponse")
    public ListMeasureDefinitionWrapper getMeasureDefinition();

}
